apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - name: my-front
          imagePullPolicy: Always
          image: seungjusuh/my-nginx:latest
          ports:
            - containerPort: 80
